### ISSUE TITLE
Request to re-upload pre-trained models

### ISSUE THREAD

**Issue by playdasegunda** [olvrhhn/audio_super_resolution#1]
Hello, we would love to test the audio_super_resolution, but github limits files to a maximum of 100mb, would it be possible to upload the models to another host? preferably google drive? Thanks in advance.

**Comment by olvrhhn** [comment]
Hey @lucasbr15, sorry I didn't realize that. I have added the checkpoints to a google drive. You can find the links in the README. Keep in mind that all the checkpoints use a ration of 4. Good luck with your project!
