### ISSUE TITLE
Request to update the link of pre-trained models

### ISSUE THREAD

**Issue by zelinwangnju** [olvrhhn/audio_super_resolution#4]
Hello, I noticed that the links of checkpoint VTCK SingleSpeaker and GTZAN (Genre: Blues) are the same (both link to GTZAN). Can you update the checkpoint of VTCK SingleSpeaker?

**Comment by olvrhhn** [comment]
Hi, 

thanks for pointing that out. I just updated the link. It should be working now. 

Best 
Oliver
